<?php
/**
 * selfheal_seal.php — seal the reporting credential into the module.
 * spec: spec/selfheal.md §4.2
 *
 * The plaintext token is read from STDIN or the SELFHEAL_SEAL_INPUT env var,
 * NEVER from an argument (arguments end up in shell history and in `ps`).
 * Output is selfheal/token.php, holding the sealed blob and nothing else.
 *
 *   php selfheal_seal.php                 # asks on stdin, writes token.php
 *   php selfheal_seal.php --local         # writes token.local.php instead
 *   php selfheal_seal.php --print         # prints the blob, writes nothing
 *   php selfheal_seal.php --check         # can the installed blob be opened?
 *   php selfheal_seal.php --remove        # delete the blob (tokenless install)
 *
 * --local is for an OPERATOR sealing their own token: that file is preserved
 * across updates and takes priority. The developer shipping the module uses the
 * plain form, so a new release can rotate the credential everywhere.
 *
 * THE TOKEN MUST BE a fine-grained GitHub PAT limited to the single repository
 * this module reports to, with the single permission "Issues: Read and write".
 * Sealing hides it from scanners, logs and casual reading — it does not hide it
 * from someone who owns the server. A token with any other scope must never be
 * sealed into distributed code.
 */

declare(strict_types=1);

if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;                               // never reachable over HTTP
}

require_once __DIR__ . '/selfheal/bootstrap.php';

use Selfheal\Vault;

$args   = array_slice($argv, 1);
$flag   = static function (string $name) use ($args): bool { return in_array('--' . $name, $args, true); };
$local  = in_array('--local', $args, true);
$name   = $local ? Vault::LOCAL_TOKEN_FILE : Vault::TOKEN_FILE;
$target = __DIR__ . '/selfheal/' . $name;

/* ── --check ── */
if ($flag('check')) {
    $src = Vault::source();
    echo 'источник учётных данных: ' . $src . "\n";
    if ($src === 'none') { echo "токен не установлен (модуль работает, отправка отчётов недоступна)\n"; exit(1); }
    $t = Vault::token();
    if ($t === '') { echo "блоб есть, но не расшифровывается — пересоздайте его\n"; exit(1); }
    echo 'токен открывается, отпечаток: ' . Vault::fingerprint() . "\n";
    echo 'форма: ' . (preg_match('~^(gh[pousr]_|github_pat_)~', $t) === 1 ? 'похож на GitHub PAT' : 'нестандартная') . "\n";
    exit(0);
}

/* ── --remove ── */
if ($flag('remove')) {
    if (!is_file($target)) { echo "нечего удалять\n"; exit(0); }
    if (!@unlink($target)) { fwrite(STDERR, "не удалось удалить $target\n"); exit(1); }
    echo $name . " удалён\n";
    exit(0);
}

/* ── read the plaintext ── */
$plain = (string) (getenv('SELFHEAL_SEAL_INPUT') ?: '');
if ($plain === '') {
    fwrite(STDERR, "Вставьте fine-grained GitHub PAT (Issues: RW, только этот репозиторий) и нажмите Enter.\n");
    fwrite(STDERR, "Ввод не эхо-безопасен в некоторых терминалах — лучше: SELFHEAL_SEAL_INPUT=... php selfheal_seal.php\n> ");
    $plain = trim((string) fgets(STDIN));
}
$plain = trim($plain);
if ($plain === '') { fwrite(STDERR, "пустой ввод — ничего не сделано\n"); exit(1); }
if (strlen($plain) < 20) { fwrite(STDERR, "это не похоже на токен (короче 20 символов)\n"); exit(1); }

if (preg_match('~^(gh[pousr]_|github_pat_)~', $plain) !== 1) {
    fwrite(STDERR, "ВНИМАНИЕ: строка не похожа на GitHub PAT. Продолжаю, но проверьте, что вставили.\n");
}
if (strpos($plain, 'ghp_') === 0) {
    fwrite(STDERR, "ВНИМАНИЕ: ghp_ — это classic PAT, у него слишком широкие права.\n"
        . "         Создайте fine-grained токен (github_pat_…) только на этот репозиторий,\n"
        . "         только с правом Issues: Read and write.\n");
}

$blob = Vault::seal($plain);
if ($blob === '' || Vault::open($blob) !== $plain) {
    fwrite(STDERR, "запечатывание не прошло самопроверку — файл не изменён\n");
    exit(1);
}

if ($flag('print')) {
    echo $blob . "\n";
    exit(0);
}

$php = "<?php\n"
     . "/**\n"
     . " * Sealed reporting credential — generated by selfheal_seal.php.\n"
     . " * Do NOT edit by hand. Do NOT put a plaintext token here.\n"
     . " * Sealed, not secret: see the honesty notice in selfheal/Vault.php.\n"
     . " * Scope of the token inside: Issues Read+Write on " . addslashes(\Selfheal\Contract::REPO) . " and nothing else.\n"
     . ($local
        ? " * Operator-local: preserved across updates, takes priority over token.php.\n"
        : " * Shipped with the module: replaced by every update, which is how the token rotates.\n")
     . " */\n"
     . "return ['gh' => '" . addslashes($blob) . "'];\n";

if (@file_put_contents($target, $php, LOCK_EX) === false) {
    fwrite(STDERR, "не удалось записать $target\n");
    exit(1);
}
@chmod($target, 0640);

// Prove it round-trips through the real reader before declaring success.
$out = shell_exec(escapeshellcmd(PHP_BINARY) . ' ' . escapeshellarg(__FILE__) . ' --check 2>&1');
echo "записан: selfheal/" . $name . " (" . strlen($blob) . " симв. блоба)\n";
echo $out !== null ? $out : '';
echo "плейнтекст нигде не сохранён. Не забудьте: токен может быть извлечён с сервера,\n"
   . "поэтому у него должно быть ровно одно право — Issues: RW в одном репозитории.\n";
