<?php
/**
 * Sealed reporting credential — generated by selfheal_seal.php.
 * Do NOT edit by hand. Do NOT put a plaintext token here.
 * Sealed, not secret: see the honesty notice in selfheal/Vault.php.
 * Required scope of the token inside: fine-grained PAT on dansury/site_yacloud_openrouter only; Issues Read+Write is its
 * only write permission. Read-only Contents/Metadata is allowed (used by the updater).
 * Shipped with the module: replaced by every update, which is how the token rotates.
 */
return ['gh' => 'sh1:mcH66pumctDqGWenx52mI6Jt5SqHc6xQc8KTgNKXB-kQ7TYIPjrTFq6q-5KtoPk-967-R1vb-50nxxnSreZxIecZfpz8754Xxg34VZKafwBmrasCRi2GzXO8F2ksQY5l12lTasGLFOeCqbQV5NqlKQ-zkyNNHdC_ZQ'];
